# Generated by Django 5.2.3 on 2025-07-10 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_customuser_groups_customuser_is_staff_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateTimeField(),
        ),
    ]
